services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      TZ: "Asia/Jakarta"
      MARIADB_DB: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 127.0.0.1:${EXPOSE_DB_PORT}:3306
    volumes:
      - ../db-mysql:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    working_dir: /var/www
    restart: unless-stopped
    ports:
      - 127.0.0.1:${EXPOSE_APP_PORT}:80
    volumes:
      - .:/var/www
